//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.14 at 10:32:25 AM COT 
//


package rest.etb.com.co.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DatosComplementoUsuarioResult" type="{http://autenticar.etb.net.co}DatosComplemento"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datosComplementoUsuarioResult"
})
@XmlRootElement(name = "DatosComplementoUsuarioResponse")
public class DatosComplementoUsuarioResponse {

    @XmlElement(name = "DatosComplementoUsuarioResult", required = true)
    protected DatosComplemento datosComplementoUsuarioResult;

    /**
     * Gets the value of the datosComplementoUsuarioResult property.
     * 
     * @return
     *     possible object is
     *     {@link DatosComplemento }
     *     
     */
    public DatosComplemento getDatosComplementoUsuarioResult() {
        return datosComplementoUsuarioResult;
    }

    /**
     * Sets the value of the datosComplementoUsuarioResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatosComplemento }
     *     
     */
    public void setDatosComplementoUsuarioResult(DatosComplemento value) {
        this.datosComplementoUsuarioResult = value;
    }

}
