//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.14 at 10:32:25 AM COT 
//


package rest.etb.com.co.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InfoUsuario complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InfoUsuario"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="login" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="nombre" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="apellido" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="fecha" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="nombre_plan" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="telefono" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="franja" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="vel_max" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="vel_min" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="pool" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="access_password" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="espacioCorreo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="espacioPWP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="cantidadCuentas" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="displayname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="reglasBURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="claveAcceso" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InfoUsuario", propOrder = {
    "login",
    "nombre",
    "apellido",
    "fecha",
    "nombrePlan",
    "telefono",
    "franja",
    "velMax",
    "velMin",
    "pool",
    "accessPassword",
    "espacioCorreo",
    "espacioPWP",
    "cantidadCuentas",
    "displayname",
    "reglasBURL",
    "claveAcceso"
})
public class InfoUsuario {

    protected String login;
    protected String nombre;
    protected String apellido;
    protected String fecha;
    @XmlElement(name = "nombre_plan")
    protected String nombrePlan;
    protected String telefono;
    protected String franja;
    @XmlElement(name = "vel_max")
    protected String velMax;
    @XmlElement(name = "vel_min")
    protected String velMin;
    protected String pool;
    @XmlElement(name = "access_password")
    protected String accessPassword;
    protected String espacioCorreo;
    protected String espacioPWP;
    protected String cantidadCuentas;
    protected String displayname;
    protected String reglasBURL;
    protected String claveAcceso;

    /**
     * Gets the value of the login property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogin() {
        return login;
    }

    /**
     * Sets the value of the login property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogin(String value) {
        this.login = value;
    }

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombre(String value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the apellido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApellido() {
        return apellido;
    }

    /**
     * Sets the value of the apellido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApellido(String value) {
        this.apellido = value;
    }

    /**
     * Gets the value of the fecha property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFecha() {
        return fecha;
    }

    /**
     * Sets the value of the fecha property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFecha(String value) {
        this.fecha = value;
    }

    /**
     * Gets the value of the nombrePlan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombrePlan() {
        return nombrePlan;
    }

    /**
     * Sets the value of the nombrePlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombrePlan(String value) {
        this.nombrePlan = value;
    }

    /**
     * Gets the value of the telefono property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * Sets the value of the telefono property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelefono(String value) {
        this.telefono = value;
    }

    /**
     * Gets the value of the franja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFranja() {
        return franja;
    }

    /**
     * Sets the value of the franja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFranja(String value) {
        this.franja = value;
    }

    /**
     * Gets the value of the velMax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVelMax() {
        return velMax;
    }

    /**
     * Sets the value of the velMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVelMax(String value) {
        this.velMax = value;
    }

    /**
     * Gets the value of the velMin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVelMin() {
        return velMin;
    }

    /**
     * Sets the value of the velMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVelMin(String value) {
        this.velMin = value;
    }

    /**
     * Gets the value of the pool property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPool() {
        return pool;
    }

    /**
     * Sets the value of the pool property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPool(String value) {
        this.pool = value;
    }

    /**
     * Gets the value of the accessPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessPassword() {
        return accessPassword;
    }

    /**
     * Sets the value of the accessPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessPassword(String value) {
        this.accessPassword = value;
    }

    /**
     * Gets the value of the espacioCorreo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEspacioCorreo() {
        return espacioCorreo;
    }

    /**
     * Sets the value of the espacioCorreo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEspacioCorreo(String value) {
        this.espacioCorreo = value;
    }

    /**
     * Gets the value of the espacioPWP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEspacioPWP() {
        return espacioPWP;
    }

    /**
     * Sets the value of the espacioPWP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEspacioPWP(String value) {
        this.espacioPWP = value;
    }

    /**
     * Gets the value of the cantidadCuentas property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCantidadCuentas() {
        return cantidadCuentas;
    }

    /**
     * Sets the value of the cantidadCuentas property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCantidadCuentas(String value) {
        this.cantidadCuentas = value;
    }

    /**
     * Gets the value of the displayname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayname() {
        return displayname;
    }

    /**
     * Sets the value of the displayname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayname(String value) {
        this.displayname = value;
    }

    /**
     * Gets the value of the reglasBURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReglasBURL() {
        return reglasBURL;
    }

    /**
     * Sets the value of the reglasBURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReglasBURL(String value) {
        this.reglasBURL = value;
    }

    /**
     * Gets the value of the claveAcceso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaveAcceso() {
        return claveAcceso;
    }

    /**
     * Sets the value of the claveAcceso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaveAcceso(String value) {
        this.claveAcceso = value;
    }

}
