//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.14 at 10:32:25 AM COT 
//


package rest.etb.com.co.stub;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rest.etb.com.co.stub package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rest.etb.com.co.stub
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ObtenerDatos }
     * 
     */
    public ObtenerDatos createObtenerDatos() {
        return new ObtenerDatos();
    }

    /**
     * Create an instance of {@link ObtenerDatosResponse }
     * 
     */
    public ObtenerDatosResponse createObtenerDatosResponse() {
        return new ObtenerDatosResponse();
    }

    /**
     * Create an instance of {@link InfoUsuario }
     * 
     */
    public InfoUsuario createInfoUsuario() {
        return new InfoUsuario();
    }

    /**
     * Create an instance of {@link ObtenerDatosETB }
     * 
     */
    public ObtenerDatosETB createObtenerDatosETB() {
        return new ObtenerDatosETB();
    }

    /**
     * Create an instance of {@link ObtenerDatosETBResponse }
     * 
     */
    public ObtenerDatosETBResponse createObtenerDatosETBResponse() {
        return new ObtenerDatosETBResponse();
    }

    /**
     * Create an instance of {@link DatosComplementoUsuario }
     * 
     */
    public DatosComplementoUsuario createDatosComplementoUsuario() {
        return new DatosComplementoUsuario();
    }

    /**
     * Create an instance of {@link DatosComplementoUsuarioResponse }
     * 
     */
    public DatosComplementoUsuarioResponse createDatosComplementoUsuarioResponse() {
        return new DatosComplementoUsuarioResponse();
    }

    /**
     * Create an instance of {@link DatosComplemento }
     * 
     */
    public DatosComplemento createDatosComplemento() {
        return new DatosComplemento();
    }

    /**
     * Create an instance of {@link RestaurarClave }
     * 
     */
    public RestaurarClave createRestaurarClave() {
        return new RestaurarClave();
    }

    /**
     * Create an instance of {@link RestaurarClaveResponse }
     * 
     */
    public RestaurarClaveResponse createRestaurarClaveResponse() {
        return new RestaurarClaveResponse();
    }

    /**
     * Create an instance of {@link RestauraClaveConexion }
     * 
     */
    public RestauraClaveConexion createRestauraClaveConexion() {
        return new RestauraClaveConexion();
    }

    /**
     * Create an instance of {@link RestauraClaveConexionResponse }
     * 
     */
    public RestauraClaveConexionResponse createRestauraClaveConexionResponse() {
        return new RestauraClaveConexionResponse();
    }

    /**
     * Create an instance of {@link ValidaUsuario }
     * 
     */
    public ValidaUsuario createValidaUsuario() {
        return new ValidaUsuario();
    }

    /**
     * Create an instance of {@link ValidaUsuarioResponse }
     * 
     */
    public ValidaUsuarioResponse createValidaUsuarioResponse() {
        return new ValidaUsuarioResponse();
    }

    /**
     * Create an instance of {@link AuthADETB }
     * 
     */
    public AuthADETB createAuthADETB() {
        return new AuthADETB();
    }

    /**
     * Create an instance of {@link AuthADETBResponse }
     * 
     */
    public AuthADETBResponse createAuthADETBResponse() {
        return new AuthADETBResponse();
    }

    /**
     * Create an instance of {@link FindADETB }
     * 
     */
    public FindADETB createFindADETB() {
        return new FindADETB();
    }

    /**
     * Create an instance of {@link FindADETBResponse }
     * 
     */
    public FindADETBResponse createFindADETBResponse() {
        return new FindADETBResponse();
    }

    /**
     * Create an instance of {@link FechaCreacion }
     * 
     */
    public FechaCreacion createFechaCreacion() {
        return new FechaCreacion();
    }

    /**
     * Create an instance of {@link FechaCreacionResponse }
     * 
     */
    public FechaCreacionResponse createFechaCreacionResponse() {
        return new FechaCreacionResponse();
    }

    /**
     * Create an instance of {@link CreaUsuario }
     * 
     */
    public CreaUsuario createCreaUsuario() {
        return new CreaUsuario();
    }

    /**
     * Create an instance of {@link CreaUsuarioResponse }
     * 
     */
    public CreaUsuarioResponse createCreaUsuarioResponse() {
        return new CreaUsuarioResponse();
    }

    /**
     * Create an instance of {@link CambiaPassword }
     * 
     */
    public CambiaPassword createCambiaPassword() {
        return new CambiaPassword();
    }

    /**
     * Create an instance of {@link CambiaPasswordResponse }
     * 
     */
    public CambiaPasswordResponse createCambiaPasswordResponse() {
        return new CambiaPasswordResponse();
    }

    /**
     * Create an instance of {@link ModificarUsuario }
     * 
     */
    public ModificarUsuario createModificarUsuario() {
        return new ModificarUsuario();
    }

    /**
     * Create an instance of {@link ModificarUsuarioResponse }
     * 
     */
    public ModificarUsuarioResponse createModificarUsuarioResponse() {
        return new ModificarUsuarioResponse();
    }

    /**
     * Create an instance of {@link RestaurarParametro }
     * 
     */
    public RestaurarParametro createRestaurarParametro() {
        return new RestaurarParametro();
    }

    /**
     * Create an instance of {@link RestaurarParametroResponse }
     * 
     */
    public RestaurarParametroResponse createRestaurarParametroResponse() {
        return new RestaurarParametroResponse();
    }

    /**
     * Create an instance of {@link ConsultarParametro }
     * 
     */
    public ConsultarParametro createConsultarParametro() {
        return new ConsultarParametro();
    }

    /**
     * Create an instance of {@link ConsultarParametroResponse }
     * 
     */
    public ConsultarParametroResponse createConsultarParametroResponse() {
        return new ConsultarParametroResponse();
    }

    /**
     * Create an instance of {@link ConsultarParametroETB }
     * 
     */
    public ConsultarParametroETB createConsultarParametroETB() {
        return new ConsultarParametroETB();
    }

    /**
     * Create an instance of {@link ConsultarParametroETBResponse }
     * 
     */
    public ConsultarParametroETBResponse createConsultarParametroETBResponse() {
        return new ConsultarParametroETBResponse();
    }

    /**
     * Create an instance of {@link ConsultarCuentas }
     * 
     */
    public ConsultarCuentas createConsultarCuentas() {
        return new ConsultarCuentas();
    }

    /**
     * Create an instance of {@link ConsultarCuentasResponse }
     * 
     */
    public ConsultarCuentasResponse createConsultarCuentasResponse() {
        return new ConsultarCuentasResponse();
    }

    /**
     * Create an instance of {@link ArrayOfTuplaCuenta }
     * 
     */
    public ArrayOfTuplaCuenta createArrayOfTuplaCuenta() {
        return new ArrayOfTuplaCuenta();
    }

    /**
     * Create an instance of {@link HistorialUsuario }
     * 
     */
    public HistorialUsuario createHistorialUsuario() {
        return new HistorialUsuario();
    }

    /**
     * Create an instance of {@link HistorialUsuarioResponse }
     * 
     */
    public HistorialUsuarioResponse createHistorialUsuarioResponse() {
        return new HistorialUsuarioResponse();
    }

    /**
     * Create an instance of {@link ArrayOfTuplaHistorial }
     * 
     */
    public ArrayOfTuplaHistorial createArrayOfTuplaHistorial() {
        return new ArrayOfTuplaHistorial();
    }

    /**
     * Create an instance of {@link TuplaCuenta }
     * 
     */
    public TuplaCuenta createTuplaCuenta() {
        return new TuplaCuenta();
    }

    /**
     * Create an instance of {@link TuplaHistorial }
     * 
     */
    public TuplaHistorial createTuplaHistorial() {
        return new TuplaHistorial();
    }

}
