//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.14 at 10:32:25 AM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://autenticar.etb.net.co", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package rest.etb.com.co.stub;
